import pandas as pd

# Cargar el archivo CSV
df = pd.read_csv("crunchbase_companies.csv")  # Reemplaza "ruta_del_archivo.csv" con la ubicación de tu archivo

# Extraer y almacenar todas las industrias únicas
all_industries = set()
df['Industries'].str.split(',').apply(lambda industries: all_industries.update([industry.strip() for industry in industries]))

industry_mapping = {
    'Business':[  'Subscription Service','Real Time',    'Janitorial Service',  'Emerging Markets',  'Consumer','B2C','Skill Assessment',  'Crowdsourcing', 'Consulting','Advice', 'Scheduling','Staffing Agency','Test and Measurement', 'Market Research','Coworking', 'Productivity Tools',  'Collaboration','Creative Agency',   'Small and Medium Businesses', ],
    'Internet':['Commercial',  'Online Auctions','Marketplace', 'E-Commerce', 'E-Commerce Platforms','Price Comparison', 'Internet',  'Search Engine', 'SEO','Vertical Search','Online Forums',  'Online Portals','Professional Networking',],
    'Social':[ 'Skill Assessment',  'Crowdsourcing', 'Reputation',  'Guides',  'Tourism','Private Social Networking', 'Social','Social Media', 'Social Impact','Charity','Non Profit', 'Hospitality', ],
    'Communication':['Association','Wireless','Call Center','Technical Support', 'Peer to Peer', 'Wired Telecommunications','SMS', 'Consumer Reviews', 'Email',  'Telecommunications',    'Contact Management',     'Customer Service', 'Communication Hardware',  'Unified Communications', ],
    'Manufacturing':['Courier Service', 'Made to Order','Electronics',  'Consumer Electronics',  'Retail Technology', 'Packaging Services','Consumer Goods',   'Retail', 'Industrial Manufacturing','Manufacturing', 'Machinery Manufacturing',],
    'Product':['Personalization','Loyalty Programs', 'Human Computer Interaction',   'Usability Testing',  'UX Design', 'Product Research','Product Management','A/B Testing', 'Product Search','Product Design',  'Graphic Design',   ],
    'CleanTech':[ 'Farming','Sharing Economy',  'AgTech','Battery', 'Solar','Electric Vehicle',  'Recycling','Waste Management',  'Farmers Market','Forestry', 'Environmental Consulting','GreenTech', 'Sustainability',  'CleanTech', 'Aquaculture','Landscaping','Environmental Engineering','Natural Resources', 'Agriculture',],
    'HHRR':['Recruiting', 'Human Resources','Employment','Social Recruiting','Training', 'Virtual Workforce',  "Women's",'Employee Benefits',  'Corporate Training','Career Planning',],
    'VR/AR':['Virtual Reality', 'Virtual Assistant', 'Virtual World','Augmented Reality','Metaverse','Simulation',],
    'Sales':['Wholesale','Point of Sale','Sales Automation','Sales Enablement','Sales',  ],
    'Infrastructure':['PaaS', 'IaaS', 'Quantum Computing', 'GPU',  'Hardware','Embedded Systems', 'Warehousing','Warehouse Automation','IT Infrastructure','Infrastructure', 'Communications Infrastructure', 'Cloud Infrastructure',],
    'Spatial/Hardware':['Electronics',  'Consumer Electronics','Communication Hardware','Hardware','DSP','NFC', 'Indoor Positioning', 'Mapping Services',  'Wireless','Location Based Services', 'GPS','Navigation',  'Aerospace', 'Geospatial','Drones', 'Drone Management', 'Marine Technology', 'Automotive',],
    'Industrial':['Electric Vehicle','Robotic Process Automation (RPA)', 'Trading Platform','3D Technology', 'Mining', 'Oil and Gas','Mining Technology',   'CAD','Chemical Engineering', 'Industrial Design', 'Nanotechnology', 'Advanced Materials','Railroad',  'Automotive','Service Industry', 'Industrial Manufacturing','Machinery Manufacturing','Industrial Engineering','Industrial Automation','Industrial',  'Semiconductor','Mechanical Engineering',  'Chemical', 'Civil Engineering', 'Facility Management','Transportation',],
    'Education':['E-Learning','Language Learning', 'Higher Education', 'Education', 'EdTech',],
    'Public':['Office Administration', 'Digital Signage',   'National Security', 'Government','Public Safety','GovTech', 'Public Transportation', 'Military',  ],
    'Enterprise':['Office Administration','Management Consulting', 'Business Process Automation (BPA)', 'Outsourcing', 'Task Management','Innovation Management',  'B2B','Social CRM', 'File Sharing', 'Document Preparation',  'Document Management', 'CRM', 'Public Relations', 'Shopping', 'Desktop Apps', 'Project Management', 'Professional Services', 'Enterprise Applications','Video Conferencing', 'Enterprise Resource Planning (ERP)', 'Enterprise','Enterprise Software','Compliance',],
    'Entertainment': ['Publishing',   'Ticketing', 'Home Services', 'Gift',  'Fashion','Cannabis', 'Beauty','Digital Entertainment','Leisure', 'Gamification','Social Network', 'Event Management','Video Streaming', 'News','Video', 'Gaming','Audio', 'Social Media Management',  'Gambling','Travel',   'Photography', 'Events','Cosmetics','Social News','Shopping Mall', 'eSports', 'Communities', 'Music',  'Blogging Platforms', 'Online Games','Digital Media', 'Video Games','Photo Editing','Media and Entertainment','Content', 'Animation', 'TV Production','Content Creators','Film Production','Video Editing',],
    'BioTech':['Biometrics', 'Biotechnology','Biopharma', 'Bioinformatics','Genetics',],
    'Food':[ 'Alternative Protein',  'Restaurants', 'Catering','Dairy','Food Delivery','Grocery',  'Food Processing', 'Food and Beverage',],
    'IoT':[  'Satellite Communication','Sensor','Internet of Things','Smart Cities','Smart Home', 'Robotics',],
    'FinTech':['Prediction Markets','Bookkeeping and Payroll',  'Retirement',  'Transaction Processing', 'Livestock', 'Rental','Leasing', 'Commercial Lending', 'Risk Management',  'Credit Bureau','Credit', 'Accounting','Incubators','Lending','Micro Lending','Debt Collections',  'Debit Cards','Fraud Detection','Payments','Hedge Funds', 'Crowdfunding', 'Impact Investing', 'Angel Investment','Decentralized Finance (DeFi)','Finance','Venture Capital', 'Mortgage','Personal Finance', 'Financial Services','Financial Exchanges','Asset Management','FinTech','Smart Contracts', 'Credit Cards','Banking' 'Billing','Funding Platform','Foreign Exchange Trading','Mobile Payments', 'Wealth Management','Real Estate Investment',],
    'Software':[ 'Windows Phone',  'Computer','Mobile','Consumer Applications','Operating Systems','Consumer Software',  'Messaging','Application Performance Management',  'Open Source','IT Management','iOS','Mobile Apps','Information Technology', 'Information Services', 'Business Information Systems', 'Management Information Systems', 'Apps','DevOps', 'Information and Communications Technology (ICT)','SaaS', 'Developer Tools','Personal Development', 'Developer Platform', 'Business Development', 'Developer APIs', 'Software Engineering','Software','Embedded Software''Meeting Software', 'Google',],
    'Clinical':['Oncology','Therapeutics', 'Pharmaceutical','Clinical Trials','Hospital', 'Medical', 'Medical Device',],
    'SupplyChain': [ 'Courier Service',  'Fast-Moving Consumer Goods','Delivery Service', 'Railroad','Transportation','Public Transportation','Supply Chain Management',  'Same Day Delivery', 'Food Delivery', 'Last Mile Transportation', 'Freight Service',  'Delivery','Fleet Management', 'Shipping','Logistics',],
    'PropTech':['Home Improvement',   'Home Renovation', 'Residential',  'Real Estate Brokerage','Mortgage',  'Real Estate',  'Commercial Real Estate', 'Rental Property', 'PropTech','Property Management','Property Development', 'Building Maintenance', 'Building Material','Smart Building', 'Construction','Real Estate Investment',],
    'AI':['Intelligent Systems','Image Recognition','Chatbot', 'Semantic Search','Text Analytics','Generative AI', 'Autonomous Vehicles', 'Computer Vision','Artificial Intelligence (AI)', 'Machine Learning', 'Speech Recognition','Natural Language Processing','Predictive Analytics',],
    'Cloud':['PaaS', 'Warehouse Automation','Warehousing','Cloud Computing', 'Cloud Management', 'Cloud Infrastructure', 'Cloud Security', 'Cloud Data Services', 'Private Cloud', 'Cloud Storage'],
    'Web':['Semantic Web','Web Development','Web Hosting','Web Design', 'Web Apps'],
    'Crypto':['Blockchain','Web3', 'Virtual Goods', 'Cryptocurrency', 'Non-Fungible Token (NFT)',  'Ethereum',  'Virtual Currency', 'Smart Contracts', 'Decentralized Finance (DeFi)','Bitcoin', ],
    'Data':['Knowledge Management', 'Warehouse Automation','Warehousing','Data Integration','Data Mining','Data Governance','Database','Data Collection and Labeling','Data Visualization','Data Storage', 'Data Management', 'Data Center Automation','Data Center','Big Data','Business Intelligence', 'Analytics','Predictive Analytics',],
    'Health':['Lifestyle','Life Science', 'Physical Security','Retirement', 'Psychology',  'Sports','Fertility', 'Cannabis','Dental','Alternative Protein', 'Personal Care and Hygiene', 'Fitness',  'Medical', 'Medical Device','Electronic Health Record (EHR)','Health Care','Personal Health', 'Health Insurance','Home Health Care','Health Diagnostics', 'Mental Health', 'Wellness'],
    'InsurTech':['Quality Assurance','Property Insurance','Life Insurance','Auto Insurance', 'InsurTech','Insurance','Commercial Insurance','Health Insurance'],
    'CyberSecurity':['Privacy', 'Identity Management','E-Signature',  'Fraud Detection','Biometrics', 'Intrusion Detection','Cyber Security','Network Security','Security',],
    'Legal':['Legal Tech', 'Compliance','Procurement', 'Legal','Intellectual Property','Tax Consulting',],
    'Energy':['Energy Efficiency','Energy Management','Clean Energy','Energy','Renewable Energy',],
    'Ads':['Lead Management', 'Ad Targeting','Social Media Advertising','Advertising', 'Advertising Platforms','Ad Network','Ad Exchange','Video Advertising','Ad Server', 'Outdoor Advertising', 'Mobile Advertising',],
    'Marketing':[ 'Consumer Research', 'Lead Management', 'Lead Generation',  'Content Marketing','Brand Marketing','Digital Marketing','Marketing Automation','Marketing','App Marketing','Social Media Marketing','Affiliate Marketing', 'Email Marketing',]
}
# Imprimir el conjunto único de industrias
print(all_industries)





{'Virtual Goods', 'Autonomous Vehicles', 'Meeting Software', 'Retail', 'DevOps', 'Google', 'Video Conferencing', 'Shipping', 'Enterprise Applications', 'Building Maintenance', 'E-Signature', 'Hospitality', 'Advertising', 
 'Staffing Agency', 'Social CRM', 'Impact Investing', 'Machine Learning', 'Network Security', 'Windows Phone', 'Technical Support', 'Quantum Computing', 'Mapping Services', 'Business Development', 'Drone Management', 
 'Digital Signage', 'Residential', 'Intellectual Property', 'Information and Communications Technology (ICT)', 'Compliance', 'Developer APIs', 'Civil Engineering', 'Natural Language Processing', 'Crowdfunding', 'Rental Property', 
 'Supply Chain Management', 'PropTech', 'SMS', 'Energy Efficiency', 'Recruiting', 'Open Source', 'Wholesale', 'Advice', 'Electronic Health Record (EHR)', 'Artificial Intelligence (AI)', 'Public Relations', 'Business Intelligence', 
 'Product Design', 'Facility Management', 'Graphic Design', 'Information Technology', 'Data Integration', 'Health Care', 'Online Portals', 'Made to Order', 'Music', 'Consumer Reviews', 'Communities', 'Data Mining', 'Private Social Networking', 
 'Hedge Funds', 'A/B Testing', 'Same Day Delivery', 'Content', 'SaaS', 'Human Resources', 'Data Governance', 'Transaction Processing', 'Content Marketing', 'GreenTech', 'Marine Technology', 'Social Media Advertising', 'Web Apps', 'Product Management',
   'Chemical', 'Commercial', 'Decentralized Finance (DeFi)', 'Internet', 'Geospatial', 'Wellness', 'Email', 'Property Management', 'Environmental Consulting', 'Drones', 'Lead Generation', 'Pharmaceutical', 'Mechanical Engineering', 
   'Therapeutics', 'Transportation', 'Building Material', 'Personal Health', 'Association', 'Non-Fungible Token (NFT)', 'Charity', 'Mortgage', 'Smart Cities', 'Fertility', 'Railroad', 'Financial Exchanges', 'Online Auctions', 'Cloud Computing',
    'Shopping Mall', 'Ad Targeting', 'Ticketing', 'Bitcoin', 'Social Impact', 'eSports', 'Office Administration', 'Telecommunications', 'Property Insurance', 'Automotive', 'Commercial Lending', 'Property Development', 'Photo Editing', 'Social', 
     'NFC', 'Augmented Reality', 'Social News', 'Cosmetics', 'Communications Infrastructure', 'Events', 'Affiliate Marketing', 'Non Profit', 'Shopping', 'Cloud Management', 'Semiconductor', 'Quality Assurance', 'Virtual World', 'Trading Platform',
       'Micro Lending', 'Call Center', 'Risk Management', 'Incubators', 'Rental', 'Sustainability', 'Employment', 'Data Center Automation', 'Information Services', 'Cyber Security', 'Sharing Economy', 'Email Marketing', 'Embedded Systems', 
       'Lending', 'Infrastructure', 'Wealth Management', 'IaaS', 'Cannabis', 'Audio', 'Food Delivery', 'Oil and Gas', 'Crowdsourcing', 'Ethereum', 'Life Insurance', 'Industrial', 'Management Information Systems', 'Apps', 'Aerospace', 
       'E-Learning', 'Public Transportation', 'Asset Management', 'Mining Technology', 'Hospital', 'Foreign Exchange Trading', 'Digital Marketing', 'Real Estate Brokerage', 'Government', 'Real Estate', 'Legal Tech', 'Auto Insurance', 
       'Contact Management', 'Intrusion Detection', 'Industrial Automation', 'Generative AI', 'Procurement', 'Biometrics', 'Fleet Management', 'Debit Cards', 'Image Recognition', 'Customer Service', 'Warehouse Automation', 'Management Consulting', 
       'Wireless', 'Gaming', 'Clinical Trials', 'Accounting', 'Communication Hardware', 'Task Management', 'Home Improvement', 'Satellite Communication', 'E-Commerce', 'Dairy', 'Unified Communications', 'Sports', 'Warehousing', 'Marketplace', 
       'Genetics', 'Delivery Service', 'Prediction Markets', 'IT Infrastructure', 'Reputation', 'Vertical Search', 'Loyalty Programs', 'Leisure', 'Application Performance Management', 'Dental', 'Payments', 'Social Media Management', 'Privacy', 
       'Mobile Payments', 'Product Research', 'Brand Marketing', 'Point of Sale', 'Oncology', 'Credit Bureau', 'Consumer Research', 'Software Engineering', 'Service Industry', 'Consumer Goods', 'Embedded Software', 'Blockchain', 'Fitness', 
       'Coworking', 'Developer Tools', 'Fashion', 'PaaS', 'Livestock', 'Financial Services', 'Knowledge Management', 'InsurTech', 'Messaging', 'Hardware', 'Personal Finance', 'Health Diagnostics', 'Navigation', 'Insurance', 'Restaurants', 'Credit',
         'Alternative Protein', 'Usability Testing', 'Waste Management', 'Mobile Advertising', 'IT Management', 'Video', 'Smart Building', 'Solar', 'Beauty', 'Higher Education', 'Mining', 'Courier Service', 'Social Media', 'Virtual Assistant', 
         'Catering', 'Personalization', 'Industrial Manufacturing', 'Home Renovation', 'Speech Recognition', 'Funding Platform', 'Cryptocurrency', 'Sensor', 'Biotechnology', 'Advanced Materials', 'Identity Management', 'GPS', 'Psychology', 
         'FinTech', 'Data Visualization', 'Data Collection and Labeling', '3D Technology', 'Cloud Infrastructure', 'Credit Cards', 'Intelligent Systems', 'Personal Care and Hygiene', 'Gambling', 'Agriculture', 'Location Based Services', 'Manufacturing',
           'Language Learning', 'Publishing', 'Travel', 'Text Analytics', 'Media and Entertainment', 'E-Commerce Platforms', 'App Marketing', 'Price Comparison', 'Mental Health', 'Video Games', 'Software', 'AgTech', 'Consulting', 'Computer', 'Forestry', 
           'Desktop Apps', 'Cloud Security', 'Semantic Web', 'Personal Development', 'Chemical Engineering', 'Professional Networking', 'Career Planning', 'SEO', 'Web Development', 'UX Design', 'Simulation', 'CRM', 'Clean Energy', 'Productivity Tools', 
           'Industrial Design', 'Corporate Training', 'Sales Automation', 'Search Engine', 'Farmers Market', 'Virtual Currency', 'National Security', 'Online Forums', 'Outdoor Advertising', 'Collaboration', 'Home Services', 'Metaverse', 'Event Management',
    'Venture Capital', 'Smart Home', 'Food Processing', 'Creative Agency', 'Employee Benefits', 'Business Information Systems', 'Online Games', 'Commercial Real Estate', 'Blogging Platforms', 'Small and Medium Businesses', 'Natural Resources',
             'Environmental Engineering', 'News', 'Enterprise Resource Planning (ERP)', 'B2C', 'Ad Network', 'Digital Media', 'Data Management', 'Real Time', 'Web Hosting', 'Marketing', 'Public Safety', 'Fraud Detection', 'Electric Vehicle', 
             'Social Recruiting', 'Delivery', 'Marketing Automation', 'Machinery Manufacturing', 'CAD', 'Commercial Insurance', 'Social Network', 'Scheduling', 'Bookkeeping and Payroll', 'Analytics', 'Recycling', 'Big Data', 'Guides', 'File Sharing', 
             'Freight Service', 'Health Insurance', 'Advertising Platforms', 'Wired Telecommunications', 'Leasing', 'Landscaping', 'Security', 'Enterprise', 'Photography', 'Operating Systems', 'Project Management', 'Professional Services', 
             'Emerging Markets', 'Human Computer Interaction', 'Sales Enablement', 'Energy Management', 'Predictive Analytics', 'Content Creators', 'Bioinformatics', 'GovTech', 'Data Center', 'Robotic Process Automation (RPA)', 'Peer to Peer',
               'Skill Assessment', 'Lead Management', 'Internet of Things', 'Farming', 'Consumer Electronics', 'Life Science', 'Video Streaming', 'Smart Contracts', 'Indoor Positioning', 'Cloud Data Services', 'Gamification', 'Market Research',
                 'Retail Technology', 'Robotics', 'Digital Entertainment', 'Battery', 'Construction', 'Tourism', 'Data Storage', 'Semantic Search', 'Mobile', 'Physical Security', 'Military', 'Private Cloud', 'Social Media Marketing', 
'Finance', 'iOS', 'Fast-Moving Consumer Goods', 'Education', 'Home Health Care', 'Database', 'Consumer', 'Lifestyle', 'Last Mile Transportation', 'Product Search', 'Janitorial Service', 'Angel Investment', 'Retirement', 'Cloud Storage', 
'Web3', 'CleanTech', 'Consumer Software', 'Real Estate Investment', 'Energy', 'EdTech', 'Nanotechnology', 'Packaging Services', 'Electronics', 'Ad Exchange', 'Film Production', 'Document Management', 'Developer Platform', 'Ad Server', 
'B2B', 'GPU', 'Animation', 'Legal', 'Mobile Apps', 'DSP', "Women's", 'Virtual Workforce', 'Test and Measurement', 'Grocery', 'Gift', 'Document Preparation', 'Video Advertising', 'TV Production', 'Aquaculture', 'Outsourcing', 'Sales', 
'Chatbot', 'Tax Consulting', 'Subscription Service', 'Billing', 'Training', 'Biopharma', 'Food and Beverage', 'Virtual Reality', 'Renewable Energy', 'Web Design', 'Banking', 'Video Editing', 'Enterprise Software', 'Medical', 'Medical Device', 
'Debt Collections', 'Computer Vision', 'Industrial Engineering', 'Business Process Automation (BPA)', 'Innovation Management', 'Consumer Applications', 'Logistics'}
