export const getIndustriesToFilter = (
  industries: (keyof industryMappingType)[]
) => {
  let industriesToFilter: string[] = [];
  if (industries.length > 0) {
    industries.forEach((industry) => {
      console.log(industryMapping[industry]);
      industriesToFilter = industriesToFilter.concat(industryMapping[industry]);
    });
  } else {
    industriesToFilter.concat(Object.values(industryMapping).flat());
  }
  return industriesToFilter;
};

export type industryMappingType = {
  Business: string[];
  Internet: string[];
  Social: string[];
  Communication: string[];
  Manufacturing: string[];
  Product: string[];
  CleanTech: string[];
  HHRR: string[];
  "VR/AR": string[];
  Sales: string[];
  Infrastructure: string[];
  "Spatial/Hardware": string[];
  Industrial: string[];
  Education: string[];
  Public: string[];
  Enterprise: string[];
  Entertainment: string[];
  BioTech: string[];
  Food: string[];
  IoT: string[];
  FinTech: string[];
  Software: string[];
  Clinical: string[];
  SupplyChain: string[];
  PropTech: string[];
  AI: string[];
  Cloud: string[];
  Web: string[];
  Crypto: string[];
  Data: string[];
  Health: string[];
  InsurTech: string[];
  CyberSecurity: string[];
  Legal: string[];
  Energy: string[];
  Ads: string[];
  Marketing: string[];
};

export const industryMapping: industryMappingType = {
  Business: [
    "Subscription Service",
    "Real Time",
    "Janitorial Service",
    "Emerging Markets",
    "Consumer",
    "B2C",
    "Skill Assessment",
    "Crowdsourcing",
    "Consulting",
    "Advice",
    "Scheduling",
    "Staffing Agency",
    "Test and Measurement",
    "Market Research",
    "Coworking",
    "Productivity Tools",
    "Collaboration",
    "Creative Agency",
    "Small and Medium Businesses",
  ],
  Internet: [
    "Commercial",
    "Online Auctions",
    "Marketplace",
    "E-Commerce",
    "E-Commerce Platforms",
    "Price Comparison",
    "Internet",
    "Search Engine",
    "SEO",
    "Vertical Search",
    "Online Forums",
    "Online Portals",
    "Professional Networking",
  ],
  Social: [
    "Skill Assessment",
    "Crowdsourcing",
    "Reputation",
    "Guides",
    "Tourism",
    "Private Social Networking",
    "Social",
    "Social Media",
    "Social Impact",
    "Charity",
    "Non Profit",
    "Hospitality",
  ],
  Communication: [
    "Association",
    "Wireless",
    "Call Center",
    "Technical Support",
    "Peer to Peer",
    "Wired Telecommunications",
    "SMS",
    "Consumer Reviews",
    "Email",
    "Telecommunications",
    "Contact Management",
    "Customer Service",
    "Communication Hardware",
    "Unified Communications",
  ],
  Manufacturing: [
    "Courier Service",
    "Made to Order",
    "Electronics",
    "Consumer Electronics",
    "Retail Technology",
    "Packaging Services",
    "Consumer Goods",
    "Retail",
    "Industrial Manufacturing",
    "Manufacturing",
    "Machinery Manufacturing",
  ],
  Product: [
    "Personalization",
    "Loyalty Programs",
    "Human Computer Interaction",
    "Usability Testing",
    "UX Design",
    "Product Research",
    "Product Management",
    "A/B Testing",
    "Product Search",
    "Product Design",
    "Graphic Design",
  ],
  CleanTech: [
    "Farming",
    "Sharing Economy",
    "AgTech",
    "Battery",
    "Solar",
    "Electric Vehicle",
    "Recycling",
    "Waste Management",
    "Farmers Market",
    "Forestry",
    "Environmental Consulting",
    "GreenTech",
    "Sustainability",
    "CleanTech",
    "Aquaculture",
    "Landscaping",
    "Environmental Engineering",
    "Natural Resources",
    "Agriculture",
  ],
  HHRR: [
    "Recruiting",
    "Human Resources",
    "Employment",
    "Social Recruiting",
    "Training",
    "Virtual Workforce",
    "Women's",
    "Employee Benefits",
    "Corporate Training",
    "Career Planning",
  ],
  "VR/AR": [
    "Virtual Reality",
    "Virtual Assistant",
    "Virtual World",
    "Augmented Reality",
    "Metaverse",
    "Simulation",
  ],
  Sales: [
    "Wholesale",
    "Point of Sale",
    "Sales Automation",
    "Sales Enablement",
    "Sales",
  ],
  Infrastructure: [
    "PaaS",
    "IaaS",
    "Quantum Computing",
    "GPU",
    "Hardware",
    "Embedded Systems",
    "Warehousing",
    "Warehouse Automation",
    "IT Infrastructure",
    "Infrastructure",
    "Communications Infrastructure",
    "Cloud Infrastructure",
  ],
  "Spatial/Hardware": [
    "Electronics",
    "Consumer Electronics",
    "Communication Hardware",
    "Hardware",
    "DSP",
    "NFC",
    "Indoor Positioning",
    "Mapping Services",
    "Wireless",
    "Location Based Services",
    "GPS",
    "Navigation",
    "Aerospace",
    "Geospatial",
    "Drones",
    "Drone Management",
    "Marine Technology",
    "Automotive",
  ],
  Industrial: [
    "Electric Vehicle",
    "Robotic Process Automation (RPA)",
    "Trading Platform",
    "3D Technology",
    "Mining",
    "Oil and Gas",
    "Mining Technology",
    "CAD",
    "Chemical Engineering",
    "Industrial Design",
    "Nanotechnology",
    "Advanced Materials",
    "Railroad",
    "Automotive",
    "Service Industry",
    "Industrial Manufacturing",
    "Machinery Manufacturing",
    "Industrial Engineering",
    "Industrial Automation",
    "Industrial",
    "Semiconductor",
    "Mechanical Engineering",
    "Chemical",
    "Civil Engineering",
    "Facility Management",
    "Transportation",
  ],
  Education: [
    "E-Learning",
    "Language Learning",
    "Higher Education",
    "Education",
    "EdTech",
  ],
  Public: [
    "Office Administration",
    "Digital Signage",
    "National Security",
    "Government",
    "Public Safety",
    "GovTech",
    "Public Transportation",
    "Military",
  ],
  Enterprise: [
    "Office Administration",
    "Management Consulting",
    "Business Process Automation (BPA)",
    "Outsourcing",
    "Task Management",
    "Innovation Management",
    "B2B",
    "Social CRM",
    "File Sharing",
    "Document Preparation",
    "Document Management",
    "CRM",
    "Public Relations",
    "Shopping",
    "Desktop Apps",
    "Project Management",
    "Professional Services",
    "Enterprise Applications",
    "Video Conferencing",
    "Enterprise Resource Planning (ERP)",
    "Enterprise",
    "Enterprise Software",
    "Compliance",
  ],
  Entertainment: [
    "Publishing",
    "Ticketing",
    "Home Services",
    "Gift",
    "Fashion",
    "Cannabis",
    "Beauty",
    "Digital Entertainment",
    "Leisure",
    "Gamification",
    "Social Network",
    "Event Management",
    "Video Streaming",
    "News",
    "Video",
    "Gaming",
    "Audio",
    "Social Media Management",
    "Gambling",
    "Travel",
    "Photography",
    "Events",
    "Cosmetics",
    "Social News",
    "Shopping Mall",
    "eSports",
    "Communities",
    "Music",
    "Blogging Platforms",
    "Online Games",
    "Digital Media",
    "Video Games",
    "Photo Editing",
    "Media and Entertainment",
    "Content",
    "Animation",
    "TV Production",
    "Content Creators",
    "Film Production",
    "Video Editing",
  ],
  BioTech: [
    "Biometrics",
    "Biotechnology",
    "Biopharma",
    "Bioinformatics",
    "Genetics",
  ],
  Food: [
    "Alternative Protein",
    "Restaurants",
    "Catering",
    "Dairy",
    "Food Delivery",
    "Grocery",
    "Food Processing",
    "Food and Beverage",
  ],
  IoT: [
    "Satellite Communication",
    "Sensor",
    "Internet of Things",
    "Smart Cities",
    "Smart Home",
    "Robotics",
  ],
  FinTech: [
    "Prediction Markets",
    "Bookkeeping and Payroll",
    "Retirement",
    "Transaction Processing",
    "Livestock",
    "Rental",
    "Leasing",
    "Commercial Lending",
    "Risk Management",
    "Credit Bureau",
    "Credit",
    "Accounting",
    "Incubators",
    "Lending",
    "Micro Lending",
    "Debt Collections",
    "Debit Cards",
    "Fraud Detection",
    "Payments",
    "Hedge Funds",
    "Crowdfunding",
    "Impact Investing",
    "Angel Investment",
    "Decentralized Finance (DeFi)",
    "Finance",
    "Venture Capital",
    "Mortgage",
    "Personal Finance",
    "Financial Services",
    "Financial Exchanges",
    "Asset Management",
    "FinTech",
    "Smart Contracts",
    "Credit Cards",
    "Banking",
    "Billing",
    "Funding Platform",
    "Foreign Exchange Trading",
    "Mobile Payments",
    "Wealth Management",
    "Real Estate Investment",
  ],
  Software: [
    "Windows Phone",
    "Computer",
    "Mobile",
    "Consumer Applications",
    "Operating Systems",
    "Consumer Software",
    "Messaging",
    "Application Performance Management",
    "Open Source",
    "IT Management",
    "iOS",
    "Mobile Apps",
    "Information Technology",
    "Information Services",
    "Business Information Systems",
    "Management Information Systems",
    "Apps",
    "DevOps",
    "Information and Communications Technology (ICT)",
    "SaaS",
    "Developer Tools",
    "Personal Development",
    "Developer Platform",
    "Business Development",
    "Developer APIs",
    "Software Engineering",
    "Software",
    "Embedded Software",
    "Meeting Software",
    "Google",
  ],
  Clinical: [
    "Oncology",
    "Therapeutics",
    "Pharmaceutical",
    "Clinical Trials",
    "Hospital",
    "Medical",
    "Medical Device",
  ],
  SupplyChain: [
    "Courier Service",
    "Fast-Moving Consumer Goods",
    "Delivery Service",
    "Railroad",
    "Transportation",
    "Public Transportation",
    "Supply Chain Management",
    "Same Day Delivery",
    "Food Delivery",
    "Last Mile Transportation",
    "Freight Service",
    "Delivery",
    "Fleet Management",
    "Shipping",
    "Logistics",
  ],
  PropTech: [
    "Home Improvement",
    "Home Renovation",
    "Residential",
    "Real Estate Brokerage",
    "Mortgage",
    "Real Estate",
    "Commercial Real Estate",
    "Rental Property",
    "PropTech",
    "Property Management",
    "Property Development",
    "Building Maintenance",
    "Building Material",
    "Smart Building",
    "Construction",
    "Real Estate Investment",
  ],
  AI: [
    "Intelligent Systems",
    "Image Recognition",
    "Chatbot",
    "Semantic Search",
    "Text Analytics",
    "Generative AI",
    "Autonomous Vehicles",
    "Computer Vision",
    "Artificial Intelligence (AI)",
    "Machine Learning",
    "Speech Recognition",
    "Natural Language Processing",
    "Predictive Analytics",
  ],
  Cloud: [
    "PaaS",
    "Warehouse Automation",
    "Warehousing",
    "Cloud Computing",
    "Cloud Management",
    "Cloud Infrastructure",
    "Cloud Security",
    "Cloud Data Services",
    "Private Cloud",
    "Cloud Storage",
  ],
  Web: [
    "Semantic Web",
    "Web Development",
    "Web Hosting",
    "Web Design",
    "Web Apps",
  ],
  Crypto: [
    "Blockchain",
    "Web3",
    "Virtual Goods",
    "Cryptocurrency",
    "Non-Fungible Token (NFT)",
    "Ethereum",
    "Virtual Currency",
    "Smart Contracts",
    "Decentralized Finance (DeFi)",
    "Bitcoin",
  ],
  Data: [
    "Knowledge Management",
    "Warehouse Automation",
    "Warehousing",
    "Data Integration",
    "Data Mining",
    "Data Governance",
    "Database",
    "Data Collection and Labeling",
    "Data Visualization",
    "Data Storage",
    "Data Management",
    "Data Center Automation",
    "Data Center",
    "Big Data",
    "Business Intelligence",
    "Analytics",
    "Predictive Analytics",
  ],
  Health: [
    "Lifestyle",
    "Life Science",
    "Physical Security",
    "Retirement",
    "Psychology",
    "Sports",
    "Fertility",
    "Cannabis",
    "Dental",
    "Alternative Protein",
    "Personal Care and Hygiene",
    "Fitness",
    "Medical",
    "Medical Device",
    "Electronic Health Record (EHR)",
    "Health Care",
    "Personal Health",
    "Health Insurance",
    "Home Health Care",
    "Health Diagnostics",
    "Mental Health",
    "Wellness",
  ],
  InsurTech: [
    "Quality Assurance",
    "Property Insurance",
    "Life Insurance",
    "Auto Insurance",
    "InsurTech",
    "Insurance",
    "Commercial Insurance",
    "Health Insurance",
  ],
  CyberSecurity: [
    "Privacy",
    "Identity Management",
    "E-Signature",
    "Fraud Detection",
    "Biometrics",
    "Intrusion Detection",
    "Cyber Security",
    "Network Security",
    "Security",
  ],
  Legal: [
    "Legal Tech",
    "Compliance",
    "Procurement",
    "Legal",
    "Intellectual Property",
    "Tax Consulting",
  ],
  Energy: [
    "Energy Efficiency",
    "Energy Management",
    "Clean Energy",
    "Energy",
    "Renewable Energy",
  ],
  Ads: [
    "Lead Management",
    "Ad Targeting",
    "Social Media Advertising",
    "Advertising",
    "Advertising Platforms",
    "Ad Network",
    "Ad Exchange",
    "Video Advertising",
    "Ad Server",
    "Outdoor Advertising",
    "Mobile Advertising",
  ],
  Marketing: [
    "Consumer Research",
    "Lead Management",
    "Lead Generation",
    "Content Marketing",
    "Brand Marketing",
    "Digital Marketing",
    "Marketing Automation",
    "Marketing",
    "App Marketing",
    "Social Media Marketing",
    "Affiliate Marketing",
    "Email Marketing",
  ],
} as const;
